# leverage the renci python base image
FROM renciorg/renci-python-image:v0.0.1

# set up working directory
WORKDIR /app

# Install dependencies
ADD requirements-lock.txt .
RUN pip install -r requirements-lock.txt

# Add the rest of the code and install package
ADD . .

RUN pip install .

CMD python -m unittest discover ./tests
